/* v1 URI 清单。ANY 保留旧回调内部的方法判断及原有 404 行为。
 * 新接口可以注册单独的方法槽位；迁移不改变既有业务契约。
 * 第四参为 F2 日志脱敏开关：true 的路由（口令类接口）日志不记录请求体。 */
static void RouteHTTP_Init(void)
{
    RouteInfo* brand;
    G_StaticRouteTableHTTP = xrtMapCreate(sizeof(RouteInfo));
	AddStaticRouteHTTP("/", XHTTP_METHOD_ANY, Request_Site_Home, false);
	AddStaticRouteHTTP("/admin", XHTTP_METHOD_ANY, Request_Index, false);
	AddStaticRouteHTTP("/admin/login", XHTTP_METHOD_ANY, Request_Login, true);
	AddStaticRouteHTTP("/admin/logout", XHTTP_METHOD_ANY, Request_Logout, false);
	AddStaticRouteHTTP("/brand/admin", XHTTP_METHOD_ANY, Request_Admin_Brand, false);
	AddStaticRouteHTTP("/admin/menu", XHTTP_METHOD_ANY, Request_Menu, false);
	AddStaticRouteHTTP("/admin/view/home", XHTTP_METHOD_ANY, Request_View_Home, false);
	AddStaticRouteHTTP("/admin/view/logs", XHTTP_METHOD_ANY, Request_View_Logs, false);
	AddStaticRouteHTTP("/admin/logs", XHTTP_METHOD_ANY, Request_Logs, false);
	AddStaticRouteHTTP("/admin/logs/clear", XHTTP_METHOD_ANY, Request_Logs_Clear, false);
	AddStaticRouteHTTP("/admin/view/tool/reload", XHTTP_METHOD_ANY, Request_View_Tool_Reload, false);
	AddStaticRouteHTTP("/admin/tool/reload/template", XHTTP_METHOD_ANY, Request_Tool_Reload_Template, false);
	AddStaticRouteHTTP("/admin/tool/reload/host", XHTTP_METHOD_ANY, Request_Tool_Reload_Host, false);
	AddStaticRouteHTTP("/admin/tool/reload/server", XHTTP_METHOD_ANY, Request_Tool_Reload_Server, false);
	AddStaticRouteHTTP("/admin/tool/reload/xs", XHTTP_METHOD_ANY, Request_Tool_Reload_XS, false);
	AddStaticRouteHTTP("/admin/trace", XHTTP_METHOD_ANY, Request_Trace_Overview, false);
	AddStaticRouteHTTP("/admin/trace/session", XHTTP_METHOD_ANY, Request_Trace_Session, false);
	AddStaticRouteHTTP("/admin/trace/option", XHTTP_METHOD_ANY, Request_Trace_Option, false);
	AddStaticRouteHTTP("/admin/trace/auth", XHTTP_METHOD_ANY, Request_Trace_Auth, false);
	AddStaticRouteHTTP("/admin/trace/route", XHTTP_METHOD_ANY, Request_Trace_Route, false);
	AddStaticRouteHTTP("/admin/option/tool/admin-entry", XHTTP_METHOD_ANY, Request_Option_AdminEntryGenerate, false);
	AddStaticRouteHTTP("/admin/view/form", XHTTP_METHOD_ANY, Request_View_Form, false);
	AddStaticRouteHTTP("/admin/form", XHTTP_METHOD_ANY, Request_Form, true);
	AddStaticRouteHTTP("/admin/view/option", XHTTP_METHOD_ANY, Request_View_Option, false);
	AddStaticRouteHTTP("/admin/option", XHTTP_METHOD_ANY, Request_Option, true);
	AddStaticRouteHTTP("/admin/view/option/files", XHTTP_METHOD_ANY, Request_View_Option_Files, false);
	AddStaticRouteHTTP("/admin/option/files", XHTTP_METHOD_ANY, Request_Option_Files, false);
	AddStaticRouteHTTP("/admin/view/option/file", XHTTP_METHOD_ANY, Request_View_Option_File, false);
	AddStaticRouteHTTP("/admin/option/file", XHTTP_METHOD_ANY, Request_Option_File, true); /* F2 掩码：保存体含配置口令明文（H3，与 /admin/option 同列） */
	AddStaticRouteHTTP("/admin/view/plugin", XHTTP_METHOD_ANY, Request_View_Plugin_List, false);
	AddStaticRouteHTTP("/admin/view/plugin/installed", XHTTP_METHOD_ANY, Request_View_Plugin_List, false); /* v1 别名 */
	AddStaticRouteHTTP("/admin/view/content/page", XHTTP_METHOD_ANY, Request_View_Content_Page, false);
	AddStaticRouteHTTP("/admin/content/pages", XHTTP_METHOD_ANY, Request_Content_Pages, false);
	AddStaticRouteHTTP("/admin/content/page", XHTTP_METHOD_ANY, Request_Content_Page, false);
	AddStaticRouteHTTP("/admin/content/page/save", XHTTP_METHOD_ANY, Request_Content_Page_Save, false);
	AddStaticRouteHTTP("/admin/content/page/delete", XHTTP_METHOD_ANY, Request_Content_Page_Delete, false);
	{ /* 前台站点路由：免鉴权免日志 */
		RouteInfo* site;
		AddStaticRouteHTTP("/features", XHTTP_METHOD_ANY, Request_Site_Features, false);
		AddStaticRouteHTTP("/plugins", XHTTP_METHOD_ANY, Request_Site_Plugins, false);
		AddStaticRouteHTTP("/capabilities", XHTTP_METHOD_ANY, Request_Site_Capabilities, false);
		AddStaticRouteHTTP("/content-system", XHTTP_METHOD_ANY, Request_Site_ContentSystem, false);
		AddStaticRouteHTTP("/docs", XHTTP_METHOD_ANY, Request_Site_Docs, false);
	AddStaticRouteHTTP("/docs/plugin", XHTTP_METHOD_ANY, Request_Site_Docs, false);
	AddStaticRouteHTTP("/docs/content", XHTTP_METHOD_ANY, Request_Site_Docs, false);
	AddStaticRouteHTTP("/docs/capability", XHTTP_METHOD_ANY, Request_Site_Docs, false);
		AddStaticRouteHTTP("/download", XHTTP_METHOD_ANY, Request_Site_Download, false);
		AddStaticRouteHTTP("/demo", XHTTP_METHOD_ANY, Request_Site_Demo, false);
		(void)site;
	}
	AddStaticRouteHTTP("/admin/view/template/form_demo", XHTTP_METHOD_ANY, Request_View_Template_FormDemo, false);
	AddStaticRouteHTTP("/admin/template/rebuild", XHTTP_METHOD_ANY, Request_Tool_Reload_Template, false);
	AddStaticRouteHTTP("/admin/view/content", XHTTP_METHOD_ANY, Request_View_Content_Index, false);
	AddStaticRouteHTTP("/admin/view/content/editor", XHTTP_METHOD_ANY, Request_View_Content_Editor, false);
	AddStaticRouteHTTP("/admin/view/content/packs", XHTTP_METHOD_ANY, Request_View_Content_Packs, false);
	AddStaticRouteHTTP("/admin/view/content/pack-store", XHTTP_METHOD_ANY, Request_View_Content_PackStore, false);
	AddStaticRouteHTTP("/admin/content/types", XHTTP_METHOD_ANY, Request_Content_Types, false);
	AddStaticRouteHTTP("/admin/content/type", XHTTP_METHOD_ANY, Request_Content_Type, false);
	AddStaticRouteHTTP("/admin/content/save", XHTTP_METHOD_ANY, Request_Content_Save, false);
	AddStaticRouteHTTP("/admin/content/delete", XHTTP_METHOD_ANY, Request_Content_Delete, false);
	AddStaticRouteHTTP("/admin/content/revisions", XHTTP_METHOD_ANY, Request_Content_Revisions, false);
	AddStaticRouteHTTP("/admin/content/generations", XHTTP_METHOD_ANY, Request_Content_Generations, false);
	AddStaticRouteHTTP("/admin/content/advisor", XHTTP_METHOD_ANY, Request_Content_Advisor, false);
	AddStaticRouteHTTP("/admin/content/generate", XHTTP_METHOD_ANY, Request_Content_Generate, false);
	AddStaticRouteHTTP("/admin/content/packs", XHTTP_METHOD_ANY, Request_Content_Packs, false);
	AddStaticRouteHTTP("/admin/content/pack", XHTTP_METHOD_ANY, Request_Content_Pack, false);
	AddStaticRouteHTTP("/admin/content/pack/form", XHTTP_METHOD_ANY, Request_Content_Pack_Form, false);
	AddStaticRouteHTTP("/admin/content/pack/options", XHTTP_METHOD_ANY, Request_Content_Pack_Options, false);
	AddStaticRouteHTTP("/admin/content/templates", XHTTP_METHOD_ANY, Request_Content_Templates, false);
    AddStaticRouteHTTP("/admin/view/plugin/store", XHTTP_METHOD_ANY, Request_View_Plugin_Store, false);
    AddStaticRouteHTTP("/admin/plugin/list", XHTTP_METHOD_ANY, Request_Plugin_List, false);
    AddStaticRouteHTTP("/admin/plugin/get", XHTTP_METHOD_ANY, Request_Plugin_Get, false);
    AddStaticRouteHTTP("/admin/plugin/enable", XHTTP_METHOD_ANY, Request_Plugin_Enable, false);
    AddStaticRouteHTTP("/admin/plugin/disable", XHTTP_METHOD_ANY, Request_Plugin_Disable, false);
    AddStaticRouteHTTP("/admin/plugin/reload", XHTTP_METHOD_ANY, Request_Plugin_Reload, false);
    AddStaticRouteHTTP("/admin/plugin/settings", XHTTP_METHOD_ANY, Request_Plugin_Settings, false);
    AddStaticRouteHTTP("/admin/plugin/export", XHTTP_METHOD_ANY, Request_Plugin_Export, false);
    AddStaticRouteHTTP("/admin/plugin/import", XHTTP_METHOD_ANY, Request_Plugin_Import, false);
    AddStaticRouteHTTP("/admin/option/file/menu", XHTTP_METHOD_ANY, Request_Option_File_Menu, false);
	AddStaticRouteHTTP("/admin/auth/user", XHTTP_METHOD_ANY, Request_Auth_User, true);
	AddStaticRouteHTTP("/admin/auth/user/repwd", XHTTP_METHOD_ANY, Request_Auth_User_Repwd, true);
	AddStaticRouteHTTP("/admin/view/auth/user", XHTTP_METHOD_ANY, Request_View_Auth_User, false);
	AddStaticRouteHTTP("/admin/view/auth/user/add", XHTTP_METHOD_ANY, Request_View_Auth_User_Add, false);
	AddStaticRouteHTTP("/admin/view/auth/user/edit", XHTTP_METHOD_ANY, Request_View_Auth_User_Edit, false);
	AddStaticRouteHTTP("/admin/auth/role", XHTTP_METHOD_ANY, Request_Auth_Role, false);
	AddStaticRouteHTTP("/admin/view/auth/role", XHTTP_METHOD_ANY, Request_View_Auth_Role, false);
	AddStaticRouteHTTP("/admin/view/auth/role/add", XHTTP_METHOD_ANY, Request_View_Auth_Role_Add, false);
	AddStaticRouteHTTP("/admin/view/auth/role/edit", XHTTP_METHOD_ANY, Request_View_Auth_Role_Edit, false);
	AddStaticRouteHTTP("/admin/auth/group", XHTTP_METHOD_ANY, Request_Auth_Group, false);
	AddStaticRouteHTTP("/admin/view/auth/group", XHTTP_METHOD_ANY, Request_View_Auth_Group, false);
	AddStaticRouteHTTP("/admin/view/auth/group/add", XHTTP_METHOD_ANY, Request_View_Auth_Group_Add, false);
	AddStaticRouteHTTP("/admin/view/auth/group/edit", XHTTP_METHOD_ANY, Request_View_Auth_Group_Edit, false);
	AddStaticRouteHTTP("/admin/auth/auth", XHTTP_METHOD_ANY, Request_Auth_Auth, false);
	AddStaticRouteHTTP("/admin/view/auth/auth", XHTTP_METHOD_ANY, Request_View_Auth_Auth, false);
	AddStaticRouteHTTP("/admin/view/auth/auth/add", XHTTP_METHOD_ANY, Request_View_Auth_Auth_Add, false);
	AddStaticRouteHTTP("/admin/view/auth/auth/edit", XHTTP_METHOD_ANY, Request_View_Auth_Auth_Edit, false);
	AddStaticRouteHTTP("/admin/auth/uris", XHTTP_METHOD_ANY, Request_Auth_URIs, false);
	AddStaticRouteHTTP("/admin/view/auth/uris", XHTTP_METHOD_ANY, Request_View_Auth_URIs, false);
	AddStaticRouteHTTP("/admin/view/auth/uris/edit", XHTTP_METHOD_ANY, Request_View_Auth_URIs_Edit, false);
	AddStaticRouteHTTP("/admin/option/menu", XHTTP_METHOD_ANY, Request_Option_Menu, false);
	AddStaticRouteHTTP("/admin/view/option/menu", XHTTP_METHOD_ANY, Request_View_Option_Menu, false);
	AddStaticRouteHTTP("/admin/view/option/menu/add", XHTTP_METHOD_ANY, Request_View_Option_Menu_Add, false);
	AddStaticRouteHTTP("/admin/view/option/menu/add/category", XHTTP_METHOD_ANY, Request_View_Option_Menu_Add_Category, false);
	AddStaticRouteHTTP("/admin/view/option/menu/edit", XHTTP_METHOD_ANY, Request_View_Option_Menu_Edit, false);
	AddStaticRouteHTTP("/admin/member/user", XHTTP_METHOD_ANY, Request_Member_User, true);
	AddStaticRouteHTTP("/admin/member/user/repwd", XHTTP_METHOD_ANY, Request_Member_User_Repwd, true);
	AddStaticRouteHTTP("/admin/member/user/balance", XHTTP_METHOD_ANY, Request_Member_User_Balance, false);
	AddStaticRouteHTTP("/admin/view/member/user", XHTTP_METHOD_ANY, Request_View_Member_User, false);
	AddStaticRouteHTTP("/admin/view/member/user/add", XHTTP_METHOD_ANY, Request_View_Member_User_Add, false);
	AddStaticRouteHTTP("/admin/view/member/user/edit", XHTTP_METHOD_ANY, Request_View_Member_User_Edit, false);
	AddStaticRouteHTTP("/admin/view/member/user/balance", XHTTP_METHOD_ANY, Request_View_Member_User_Balance, false);
	AddStaticRouteHTTP("/admin/member/group", XHTTP_METHOD_ANY, Request_Member_Group, false);
	AddStaticRouteHTTP("/admin/view/member/group", XHTTP_METHOD_ANY, Request_View_Member_Group, false);
	AddStaticRouteHTTP("/admin/view/member/group/add", XHTTP_METHOD_ANY, Request_View_Member_Group_Add, false);
	AddStaticRouteHTTP("/admin/view/member/group/edit", XHTTP_METHOD_ANY, Request_View_Member_Group_Edit, false);
	AddStaticRouteHTTP("/admin/member/authgroup", XHTTP_METHOD_ANY, Request_Member_AuthGroup, false);
	AddStaticRouteHTTP("/admin/view/member/authgroup", XHTTP_METHOD_ANY, Request_View_Member_AuthGroup, false);
	AddStaticRouteHTTP("/admin/view/member/authgroup/add", XHTTP_METHOD_ANY, Request_View_Member_AuthGroup_Add, false);
	AddStaticRouteHTTP("/admin/view/member/authgroup/edit", XHTTP_METHOD_ANY, Request_View_Member_AuthGroup_Edit, false);
	AddStaticRouteHTTP("/admin/member/auth", XHTTP_METHOD_ANY, Request_Member_Auth, false);
	AddStaticRouteHTTP("/admin/view/member/auth", XHTTP_METHOD_ANY, Request_View_Member_Auth, false);
	AddStaticRouteHTTP("/admin/view/member/auth/add", XHTTP_METHOD_ANY, Request_View_Member_Auth_Add, false);
	AddStaticRouteHTTP("/admin/view/member/auth/edit", XHTTP_METHOD_ANY, Request_View_Member_Auth_Edit, false);
	XA_IdentityRegisterRoutes();
	XA_ChallengeRegisterRoutes();
	AddStaticRouteHTTP("/api/v1/login", XHTTP_METHOD_ANY, API_Login, true);
	AddStaticRouteHTTP("/api/v1/register", XHTTP_METHOD_ANY, API_Register, true);
	AddStaticRouteHTTP("/api/v1/logout", XHTTP_METHOD_ANY, API_Logout, false);
	AddStaticRouteHTTP("/api/v1/profile", XHTTP_METHOD_ANY, API_Profile, false);
	AddStaticRouteHTTP("/api/v1/profile/password", XHTTP_METHOD_ANY, API_Password, true);
	AddStaticRouteHTTP("/api/v1/balance", XHTTP_METHOD_ANY, API_Balance, false);
	AddStaticRouteHTTP("/api/v1/balance/log", XHTTP_METHOD_ANY, API_BalanceLog, false);
	AddStaticRouteHTTP("/api/v1/notify/list", XHTTP_METHOD_ANY, API_Notify_List, false);
	AddStaticRouteHTTP("/api/v1/notify/unread_count", XHTTP_METHOD_ANY, API_Notify_UnreadCount, false);
	AddStaticRouteHTTP("/api/v1/notify/detail", XHTTP_METHOD_ANY, API_Notify_Detail, false);
	AddStaticRouteHTTP("/api/v1/notify/read", XHTTP_METHOD_ANY, API_Notify_Read, false);
	AddStaticRouteHTTP("/api/v1/notify/read_all", XHTTP_METHOD_ANY, API_Notify_ReadAll, false);
	AddStaticRouteHTTP("/api/v1/notify/delete", XHTTP_METHOD_ANY, API_Notify_Delete, false);
	AddStaticRouteHTTP("/api/v1/attachment/upload", XHTTP_METHOD_ANY, Request_Api_Attachment_Upload, false);
	AddStaticRouteHTTP("/api/v1/attachment/purchase", XHTTP_METHOD_ANY, Request_Api_Attachment_Purchase, false);
	AddStaticRouteHTTP("/api/v1/attachment/my", XHTTP_METHOD_ANY, Request_Api_Attachment_MyList, false);
	AddStaticRouteHTTP("/api/v1/attachment/purchased", XHTTP_METHOD_ANY, Request_Api_Attachment_Purchased, false);
	AddStaticRouteHTTP("/attachment", XHTTP_METHOD_GET, Request_Attachment_Access, false);
	AddStaticRouteHTTP("/admin/attachment/upload", XHTTP_METHOD_ANY, Request_Attachment_Upload, true);
	AddStaticRouteHTTP("/admin/attachment/list", XHTTP_METHOD_ANY, Request_Attachment_List, false);
	AddStaticRouteHTTP("/admin/attachment/get", XHTTP_METHOD_ANY, Request_Attachment_Get, false);
	AddStaticRouteHTTP("/admin/attachment/save", XHTTP_METHOD_ANY, Request_Attachment_Save, false);
	AddStaticRouteHTTP("/admin/attachment/delete", XHTTP_METHOD_ANY, Request_Attachment_Delete, false);
	AddStaticRouteHTTP("/admin/attachment/stats", XHTTP_METHOD_ANY, Request_Attachment_Stats, false);
	AddStaticRouteHTTP("/admin/view/attachment", XHTTP_METHOD_ANY, Request_View_Attachment_List, false);
	AddStaticRouteHTTP("/admin/view/attachment/edit", XHTTP_METHOD_ANY, Request_View_Attachment_Edit, false);
	AddStaticRouteHTTP("/admin/view/attachment/upload", XHTTP_METHOD_ANY, Request_View_Attachment_Upload, false);
	AddStaticRouteHTTP("/admin/view/attachment/stats", XHTTP_METHOD_ANY, Request_View_Attachment_Stats, false);
	AddStaticRouteHTTP("/admin/sched/tasks", XHTTP_METHOD_ANY, Request_Sched_Tasks, false);
	AddStaticRouteHTTP("/admin/sched/task", XHTTP_METHOD_ANY, Request_Sched_Task, false);
	AddStaticRouteHTTP("/admin/sched/task/save", XHTTP_METHOD_ANY, Request_Sched_Task_Save, false);
	AddStaticRouteHTTP("/admin/sched/task/delete", XHTTP_METHOD_ANY, Request_Sched_Task_Delete, false);
	AddStaticRouteHTTP("/admin/sched/task/enable", XHTTP_METHOD_ANY, Request_Sched_Task_Enable, false);
	AddStaticRouteHTTP("/admin/sched/task/run", XHTTP_METHOD_ANY, Request_Sched_Task_Run, false);
	AddStaticRouteHTTP("/admin/sched/task/copy", XHTTP_METHOD_ANY, Request_Sched_Task_Copy, false);
	AddStaticRouteHTTP("/admin/sched/task/example", XHTTP_METHOD_ANY, Request_Sched_Task_Example, false);
	AddStaticRouteHTTP("/admin/sched/task/batch_run", XHTTP_METHOD_ANY, Request_Sched_Task_Batch, false);
	AddStaticRouteHTTP("/admin/sched/task/batch_enable", XHTTP_METHOD_ANY, Request_Sched_Task_Batch, false);
	AddStaticRouteHTTP("/admin/sched/task/batch_delete", XHTTP_METHOD_ANY, Request_Sched_Task_Batch, false);
	AddStaticRouteHTTP("/admin/sched/preview", XHTTP_METHOD_ANY, Request_Sched_Preview, false);
	AddStaticRouteHTTP("/admin/sched/dashboard", XHTTP_METHOD_ANY, Request_Sched_Dashboard, false);
	AddStaticRouteHTTP("/admin/sched/logs", XHTTP_METHOD_ANY, Request_Sched_Logs, false);
	AddStaticRouteHTTP("/admin/sched/logs/clear", XHTTP_METHOD_ANY, Request_Sched_Logs_Clear, false);
	AddStaticRouteHTTP("/admin/sched/logs/export", XHTTP_METHOD_ANY, Request_Sched_Logs_Export, false);
	AddStaticRouteHTTP("/admin/sched/export", XHTTP_METHOD_ANY, Request_Sched_Export, false);
	AddStaticRouteHTTP("/admin/sched/export_selected", XHTTP_METHOD_ANY, Request_Sched_Export_Selected, false);
	AddStaticRouteHTTP("/admin/sched/import", XHTTP_METHOD_ANY, Request_Sched_Import, false);
	AddStaticRouteHTTP("/admin/view/sched", XHTTP_METHOD_ANY, Request_View_Sched_List, false);
	AddStaticRouteHTTP("/admin/view/sched/edit", XHTTP_METHOD_ANY, Request_View_Sched_Edit, false);
	AddStaticRouteHTTP("/admin/view/sched/dashboard", XHTTP_METHOD_ANY, Request_View_Sched_Dashboard, false);
	AddStaticRouteHTTP("/admin/view/sched/log", XHTTP_METHOD_ANY, Request_View_Sched_Log, false);
	AddStaticRouteHTTP("/admin/member/notify", XHTTP_METHOD_ANY, Request_Member_Notify, true);
	AddStaticRouteHTTP("/admin/view/member/notify", XHTTP_METHOD_ANY, Request_View_Member_Notify, false);
	AddStaticRouteHTTP("/admin/view/member/notify/send", XHTTP_METHOD_ANY, Request_View_Member_Notify_Send, false);
#if XADMIN_WITH_SMTP
	AddStaticRouteHTTP("/admin/member/mail", XHTTP_METHOD_ANY, Request_Member_Mail, true);
	AddStaticRouteHTTP("/admin/member/mail/status", XHTTP_METHOD_ANY, Request_Member_Mail_Status, false);
	AddStaticRouteHTTP("/admin/member/mail/run_pending", XHTTP_METHOD_ANY, Request_Member_Mail_RunPending, false);
	AddStaticRouteHTTP("/admin/member/mail/retry", XHTTP_METHOD_ANY, Request_Member_Mail_Retry, false);
	AddStaticRouteHTTP("/admin/member/mail/delete", XHTTP_METHOD_ANY, Request_Member_Mail_Delete, false);
	AddStaticRouteHTTP("/admin/option/tool/test-smtp", XHTTP_METHOD_ANY, Request_Option_Tool_TestSmtp, true);
	AddStaticRouteHTTP("/admin/view/member/mail", XHTTP_METHOD_ANY, Request_View_Member_Mail, false);
	AddStaticRouteHTTP("/admin/view/member/mail/send", XHTTP_METHOD_ANY, Request_View_Member_Mail_Send, false);
#endif
    { /* 前台站点路由免鉴权（覆盖 uris 表 isBackend=1 的种子默认）；含 v1 的 3 条 docs 别名 */
        RouteInfo* sr;
        const char* sp[] = {"/", "/features", "/plugins", "/capabilities", "/content-system", "/docs",
                            "/docs/plugin", "/docs/content", "/docs/capability", "/download", "/demo"};
        int si;
        for (si = 0; si < 11; si++) {
            sr = xrtMapGet(G_StaticRouteTableHTTP, KeyView(sp[si]));
            if (sr) { sr->bAuth = false; sr->bAdmin = false; }
        }
    }
    brand = xrtMapGet(G_StaticRouteTableHTTP, KeyViewN("/brand/admin", 12));
    if (brand) { brand->bAuth = false; brand->bAdmin = false; }
}
