CREATE TABLE IF NOT EXISTS static_rule (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL DEFAULT '',
path_pattern TEXT NOT NULL DEFAULT '',
template_name TEXT NOT NULL DEFAULT '',
status INTEGER NOT NULL DEFAULT 1,
create_time INTEGER NOT NULL DEFAULT 0,
update_time INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS static_task (
id INTEGER PRIMARY KEY AUTOINCREMENT,
rule_id INTEGER NOT NULL DEFAULT 0,
target_type TEXT NOT NULL DEFAULT '',
target_id INTEGER NOT NULL DEFAULT 0,
status INTEGER NOT NULL DEFAULT 0,
message TEXT NOT NULL DEFAULT '',
create_time INTEGER NOT NULL DEFAULT 0,
finish_time INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS static_artifact (
id INTEGER PRIMARY KEY AUTOINCREMENT,
rule_id INTEGER NOT NULL DEFAULT 0,
target_type TEXT NOT NULL DEFAULT '',
target_id INTEGER NOT NULL DEFAULT 0,
path TEXT NOT NULL DEFAULT '',
hash TEXT NOT NULL DEFAULT '',
create_time INTEGER NOT NULL DEFAULT 0,
update_time INTEGER NOT NULL DEFAULT 0,
UNIQUE(rule_id, target_type, target_id)
);
CREATE INDEX IF NOT EXISTS idx_static_task_status ON static_task(status, create_time);
CREATE INDEX IF NOT EXISTS idx_static_artifact_path ON static_artifact(path);
