str Content_StripUtf8BomTake(str sText, uint32* pSize)
{
	size_t iLen;
	str sClean;

	if ( sText == NULL ) {
		return NULL;
	}
	iLen = pSize ? (size_t)(*pSize) : strlen(sText);
	if ( iLen < 3 ) {
		return sText;
	}
	if ( ((unsigned char)sText[0] != 0xEF) || ((unsigned char)sText[1] != 0xBB) || ((unsigned char)sText[2] != 0xBF) ) {
		return sText;
	}

	sClean = xrtCopyStr(sText + 3, iLen - 3);
	xrtFree(sText);
	if ( pSize ) {
		*pSize = sClean ? (uint32)(iLen - 3) : 0;
	}
	return sClean;
}

const char* Content_RawTextOr(const char* sText, const char* sFallback)
{
	if ( (sText != NULL) && (sText[0] != '\0') ) {
		return sText;
	}
	return sFallback ? sFallback : "";
}

str Content_EscapeJsonString(const char* sText)
{
	xbuffer_struct tBuf;
	char chZero = 0;

	if ( sText == NULL ) {
		return xrtCopyStr("", 0);
	}

	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + 16));
	for ( const char* p = sText; *p; p++ ) {
		char c = *p;
		if ( c == '\\' ) {
			xrtBufferAppend(&tBuf, "\\\\", 2, XBUF_BINARY);
		} else if ( c == '"' ) {
			xrtBufferAppend(&tBuf, "\\\"", 2, XBUF_BINARY);
		} else if ( c == '\n' ) {
			xrtBufferAppend(&tBuf, "\\n", 2, XBUF_BINARY);
		} else if ( c == '\r' ) {
			xrtBufferAppend(&tBuf, "\\r", 2, XBUF_BINARY);
		} else if ( c == '\t' ) {
			xrtBufferAppend(&tBuf, "\\t", 2, XBUF_BINARY);
		} else {
			xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
		}
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_BuildGeneratedPluginJson(const char* sPluginXid, const char* sPluginTitle, const char* sDescription)
{
	str sSafeTitle = Content_EscapeJsonString(Content_RawTextOr(sPluginTitle, "Generated Content Plugin"));
	str sSafeDescription = Content_EscapeJsonString(Content_RawTextOr(sDescription, "Generated by xAdmin built-in content system"));
	str sRet = xrtFormat(
		"{\n"
		"\t\"formatVersion\": 4,\n"
		"\t\"xid\": \"%s\",\n"
		"\t\"name\": \"%s\",\n"
		"\t\"title\": \"%s\",\n"
		"\t\"description\": \"%s\",\n"
		"\t\"version\": \"1.0.0\",\n"
		"\t\"author\": \"xAdmin\",\n"
		"\t\"kind\": \"singleton\",\n"
		"\t\"runtime\": {\"compiler\":\"tcc\",\"language\":\"c\"},\n"
		"\t\"resources\": {\"page\":\"page\",\"template\":\"template\",\"option\":\"option\",\"static\":\"static\"},\n"
		"\t\"build\": {\"entry\":\"generated/main.c\",\"sources\":[\"generated/main.c\"],\"defines\":[\"XADMIN_PLUGIN=1\"]},\n"
		"\t\"compat\": {\"minHostVersion\":\"4.0.0\",\"maxHostVersion\":\"5.0.0\",\"abiVersion\":4},\n"
		"\t\"capabilities\": [\"route.public\",\"route.admin\"],\n"
		"\t\"dependencies\": {\"plugins\":[],\"services\":[],\"features\":[]},\n"
		"\t\"contributes\": {\"menus\":[],\"routes\":[],\"hooks\":[],\"events\":[]},\n"
		"\t\"defaultConfig\": \"config.defaults.json\",\n"
		"\t\"configSchema\": \"config.schema.json\",\n"
		"\t\"xadminManaged\": {\"managed\":true,\"generator\":\"content\",\"managedBy\":\"content\",\"managedType\":\"generated-plugin\",\"generatedRoot\":\"generated\",\"runtimeRoot\":\"runtime\",\"customRoot\":\"custom\"}\n"
		"}\n",
		sPluginXid,
		sPluginXid,
		Content_RawTextOr((const char*)sSafeTitle, "Generated Content Plugin"),
		Content_RawTextOr((const char*)sSafeDescription, "Generated by xAdmin built-in content system")
	);
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	if ( sSafeDescription ) xrtFree(sSafeDescription);
	return sRet;
}

const char* Content_TextOr(const char* sText, const char* sFallback)
{
	if ( (sText != NULL) && (sText[0] != '\0') ) {
		return sText;
	}
	return sFallback ? sFallback : "";
}

str Content_SanitizeSqlIdent(const char* sText, const char* sFallback)
{
	xbuffer_struct tBuf;
	char chZero = 0;
	bool bHasChar = FALSE;

	xrtBufferInit(&tBuf, 64);
	if ( sText ) {
		for ( const char* p = sText; *p; p++ ) {
			char c = *p;
			if ( ((c >= 'a') && (c <= 'z')) || ((c >= 'A') && (c <= 'Z')) || ((c >= '0') && (c <= '9')) || (c == '_') ) {
				xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
				bHasChar = TRUE;
			}
		}
	}
	if ( !bHasChar ) {
		const char* sDefault = Content_TextOr(sFallback, "content_record");
		xrtBufferAppend(&tBuf, (ptr)sDefault, (uint32)strlen(sDefault), XBUF_BINARY);
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_TemplatePath(const char* sName)
{
	if ( (AppPath == NULL) || (sName == NULL) || (sName[0] == '\0') ) {
		return NULL;
	}
	return xrtPathJoin(5, AppPath, "data", "template", "content", (str)sName);
}

str Content_LoadGeneratorTemplate(const char* sName)
{
	str sPath;
	str sText = NULL;
	size_t iSize = 0;

	sPath = Content_TemplatePath(sName);
	if ( sPath && xrtFileExists(sPath) ) {
		sText = xrtFileGetAll(sPath, &iSize);
		sText = Content_StripUtf8BomTake(sText, &iSize);
	}
	if ( sPath ) {
		xrtFree(sPath);
	}
	return sText;
}

str Content_StringReplaceAll(const char* sText, const char* sNeedle, const char* sValue)
{
	xbuffer_struct tBuf;
	const char* p;
	const char* sCursor;
	size_t iNeedleLen;
	char chZero = 0;

	if ( sText == NULL ) {
		return NULL;
	}
	if ( (sNeedle == NULL) || (sNeedle[0] == '\0') ) {
		return xrtCopyStr((str)sText, 0);
	}
	if ( sValue == NULL ) {
		sValue = "";
	}

	iNeedleLen = strlen(sNeedle);
	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + strlen(sValue) + 32));
	sCursor = sText;
	while ( (p = strstr(sCursor, sNeedle)) != NULL ) {
		if ( p > sCursor ) {
			xrtBufferAppend(&tBuf, (ptr)sCursor, (uint32)(p - sCursor), XBUF_BINARY);
		}
		xrtBufferAppend(&tBuf, (ptr)sValue, (uint32)strlen(sValue), XBUF_BINARY);
		sCursor = p + iNeedleLen;
	}
	xrtBufferAppend(&tBuf, (ptr)sCursor, (uint32)strlen(sCursor), XBUF_BINARY);
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_TemplateSet(str sTemplate, const char* sNeedle, const char* sValue)
{
	str sNext = Content_StringReplaceAll(sTemplate, sNeedle, sValue);
	if ( sTemplate ) {
		xrtFree(sTemplate);
	}
	return sNext;
}

str Content_EscapeCString(const char* sText)
{
	xbuffer_struct tBuf;
	char chZero = 0;

	if ( sText == NULL ) {
		return xrtCopyStr("", 0);
	}

	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + 16));
	for ( const char* p = sText; *p; p++ ) {
		char c = *p;
		if ( c == '\\' ) {
			xrtBufferAppend(&tBuf, "\\\\", 2, XBUF_BINARY);
		} else if ( c == '"' ) {
			xrtBufferAppend(&tBuf, "\\\"", 2, XBUF_BINARY);
		} else if ( c == '\n' ) {
			xrtBufferAppend(&tBuf, "\\n", 2, XBUF_BINARY);
		} else if ( c == '\r' ) {
			xrtBufferAppend(&tBuf, "\\r", 2, XBUF_BINARY);
		} else {
			xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
		}
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_EscapeHtml(const char* sText)
{
	xbuffer_struct tBuf;
	char chZero = 0;

	if ( sText == NULL ) {
		return xrtCopyStr("", 0);
	}

	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + 16));
	for ( const char* p = sText; *p; p++ ) {
		char c = *p;
		if ( c == '&' ) {
			xrtBufferAppend(&tBuf, "&amp;", 5, XBUF_BINARY);
		} else if ( c == '<' ) {
			xrtBufferAppend(&tBuf, "&lt;", 4, XBUF_BINARY);
		} else if ( c == '>' ) {
			xrtBufferAppend(&tBuf, "&gt;", 4, XBUF_BINARY);
		} else if ( c == '"' ) {
			xrtBufferAppend(&tBuf, "&quot;", 6, XBUF_BINARY);
		} else if ( c == '\'' ) {
			xrtBufferAppend(&tBuf, "&#39;", 5, XBUF_BINARY);
		} else {
			xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
		}
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_BuildGeneratedMainC(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("plugin.main.c.tpl");
	str sRoute = xrtFormat("/admin/view/plugin/%s", sPluginXid ? sPluginXid : "");
	str sPublicRoute = xrtFormat("/content/%s", sPluginXid ? sPluginXid : "");
	str sOptionRoute = xrtFormat("/admin/view/form?source=plugin-option&plugin=%s&file=runtime.json", sPluginXid ? sPluginXid : "");
	if ( sTemplate == NULL ) {
		if ( sRoute ) xrtFree(sRoute);
		if ( sPublicRoute ) xrtFree(sPublicRoute);
		if ( sOptionRoute ) xrtFree(sOptionRoute);
		return xrtCopyStr("", 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@ADMIN_ROUTE@@", Content_TextOr((const char*)sRoute, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@PUBLIC_ROUTE@@", Content_TextOr((const char*)sPublicRoute, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@OPTION_ROUTE@@", Content_TextOr((const char*)sOptionRoute, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@PLUGIN_XID@@", sPluginXid ? sPluginXid : "");
	if ( sRoute ) xrtFree(sRoute);
	if ( sPublicRoute ) xrtFree(sPublicRoute);
	if ( sOptionRoute ) xrtFree(sOptionRoute);
	return sTemplate;
}

str Content_BuildPluginDomIdBase(const char* sPluginXid)
{
	const char* sBase = sPluginXid ? sPluginXid : "";
	const char* sPrefix = "Content_MakePlugin_";
	size_t iPrefixLen = strlen(sPrefix);
	size_t iBaseLen = strlen(sBase);
	char* sOut = (char*)xrtMalloc(iPrefixLen + iBaseLen + 1);
	size_t iPos = 0;

	if ( sOut == NULL ) {
		return NULL;
	}
	memcpy(sOut, sPrefix, iPrefixLen);
	iPos = iPrefixLen;
	for ( size_t i = 0; i < iBaseLen; i++ ) {
		char ch = sBase[i];
		if ( ((ch >= 'a') && (ch <= 'z')) || ((ch >= 'A') && (ch <= 'Z')) || ((ch >= '0') && (ch <= '9')) ) {
			sOut[iPos++] = ch;
		} else {
			sOut[iPos++] = '_';
		}
	}
	sOut[iPos] = '\0';
	return sOut;
}

str Content_BuildManagedMainC(const char* sPluginXid, const char* sPluginTitle, const char* sMenuTitle)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_main.template.c");
	str sSafePluginTitle = Content_EscapeCString(Content_TextOr(sPluginTitle, sPluginXid ? sPluginXid : "Generated Content Plugin"));
	str sSafeMenuTitle = Content_EscapeCString(Content_TextOr(sMenuTitle, sPluginTitle ? sPluginTitle : (sPluginXid ? sPluginXid : "Generated Content Plugin")));
	if ( sTemplate == NULL ) {
		if ( sSafePluginTitle ) xrtFree(sSafePluginTitle);
		if ( sSafeMenuTitle ) xrtFree(sSafeMenuTitle);
		return xrtCopyStr("", 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_TITLE_C}}", Content_TextOr((const char*)sSafePluginTitle, ""));
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_VERSION}}", "1.0.0");
	if ( sSafeMenuTitle && sPluginTitle && sMenuTitle && strcmp((const char*)sPluginTitle, (const char*)sMenuTitle) != 0 ) {
		str sNeedle = xrtFormat("menu.title = \"%s\";", Content_TextOr((const char*)sSafePluginTitle, ""));
		str sValue = xrtFormat("menu.title = \"%s\";", Content_TextOr((const char*)sSafeMenuTitle, ""));
		if ( sNeedle && sValue ) {
			sTemplate = Content_TemplateSet(sTemplate, sNeedle, sValue);
		}
		if ( sNeedle ) xrtFree(sNeedle);
		if ( sValue ) xrtFree(sValue);
	}
	if ( sSafePluginTitle ) xrtFree(sSafePluginTitle);
	if ( sSafeMenuTitle ) xrtFree(sSafeMenuTitle);
	return sTemplate;
}

str Content_BuildManagedAdminPageHtml(const char* sPluginXid, const char* sPageKind)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_admin.template.html");
	str sDomIdBase = Content_BuildPluginDomIdBase(sPluginXid);
	str sPageDomIdBase = NULL;
	if ( sTemplate == NULL ) {
		if ( sDomIdBase ) xrtFree(sDomIdBase);
		return NULL;
	}
	sPageDomIdBase = xrtFormat("%s_%s", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin", (sPageKind && strcmp(sPageKind, "drafts") == 0) ? "Drafts" : "Articles");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_DOM_ID_BASE}}", sPageDomIdBase ? (const char*)sPageDomIdBase : (sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin"));
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_PAGE_KIND}}", sPageKind ? sPageKind : "articles");
	if ( sPageDomIdBase ) xrtFree(sPageDomIdBase);
	if ( sDomIdBase ) xrtFree(sDomIdBase);
	return sTemplate;
}

str Content_BuildManagedCategoryHtml(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_category.template.html");
	str sDomIdBase = Content_BuildPluginDomIdBase(sPluginXid);
	str sPageDomIdBase = NULL;
	if ( sTemplate == NULL ) {
		if ( sDomIdBase ) xrtFree(sDomIdBase);
		return NULL;
	}
	sPageDomIdBase = xrtFormat("%s_Categories", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_DOM_ID_BASE}}", sPageDomIdBase ? (const char*)sPageDomIdBase : (sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin_Category"));
	if ( sPageDomIdBase ) xrtFree(sPageDomIdBase);
	if ( sDomIdBase ) xrtFree(sDomIdBase);
	return sTemplate;
}

str Content_BuildManagedPublicHtml(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_public.template.html");
	str sDomIdBase = Content_BuildPluginDomIdBase(sPluginXid);
	if ( sTemplate == NULL ) {
		if ( sDomIdBase ) xrtFree(sDomIdBase);
		return NULL;
	}
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_DOM_ID_BASE}}", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_PAGE_KIND}}", "public");
	if ( sDomIdBase ) xrtFree(sDomIdBase);
	return sTemplate;
}

str Content_BuildGeneratedModelH(const char* sModelXid, const char* sTitle, const char* sPluginTitle, const char* sMenuTitle)
{
	str sSafeXid = Content_EscapeCString(sModelXid);
	str sSafeTitle = Content_EscapeCString(sTitle ? sTitle : "Generated Content Plugin");
	str sSafePluginTitle = Content_EscapeCString(Content_TextOr(sPluginTitle, sTitle ? sTitle : "Generated Content Plugin"));
	str sSafeMenuTitle = Content_EscapeCString(Content_TextOr(sMenuTitle, sTitle ? sTitle : "Generated Content Plugin"));
	str sRet;

	sRet = xrtFormat(
		"#ifndef CONTENT_PLUGIN_MODEL_H\n"
		"#define CONTENT_PLUGIN_MODEL_H\n"
		"\n"
		"#define CONTENT_MODEL_XID \"%s\"\n"
		"#define CONTENT_MODEL_TITLE \"%s\"\n"
		"#define CONTENT_PLUGIN_TITLE \"%s\"\n"
		"#define CONTENT_MENU_TITLE \"%s\"\n"
		"\n"
		"#endif\n",
		Content_TextOr((const char*)sSafeXid, ""),
		Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"),
		Content_TextOr((const char*)sSafePluginTitle, "Generated Content Plugin"),
		Content_TextOr((const char*)sSafeMenuTitle, "Generated Content Plugin")
	);
	if ( sSafeXid ) xrtFree(sSafeXid);
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	if ( sSafePluginTitle ) xrtFree(sSafePluginTitle);
	if ( sSafeMenuTitle ) xrtFree(sSafeMenuTitle);
	return sRet;
}

str Content_BuildGeneratedDbH(const char* sTableName)
{
	str sTable = Content_SanitizeSqlIdent(sTableName, "content_record");
	str sRet = xrtFormat(
		"#ifndef CONTENT_PLUGIN_DB_H\n"
		"#define CONTENT_PLUGIN_DB_H\n"
		"\n"
		"static const char* CONTENT_PLUGIN_SCHEMA_SQL =\n"
		"\t\"CREATE TABLE IF NOT EXISTS %s (\"\n"
		"\t\"id INTEGER PRIMARY KEY AUTOINCREMENT,\"\n"
		"\t\"status INTEGER NOT NULL DEFAULT 0,\"\n"
		"\t\"payload_json TEXT NOT NULL DEFAULT '{}',\"\n"
		"\t\"create_time INTEGER NOT NULL,\"\n"
		"\t\"update_time INTEGER NOT NULL DEFAULT 0,\"\n"
		"\t\"delete_time INTEGER NOT NULL DEFAULT 0\"\n"
		"\t\");\";\n"
		"\n"
		"static bool ContentPlugin_EnsureSchema(const char* sPrivateDbPath)\n"
		"{\n"
		"\tsqlite3* pDb = NULL;\n"
		"\tchar* sError = NULL;\n"
		"\tbool bOK = FALSE;\n"
		"\tif ( (sPrivateDbPath == NULL) || (sPrivateDbPath[0] == '\\0') ) return FALSE;\n"
		"\tif ( sqlite3_open_v2(sPrivateDbPath, &pDb, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_FULLMUTEX, NULL) != SQLITE_OK ) {\n"
		"\t\tif ( pDb ) sqlite3_close(pDb);\n"
		"\t\treturn FALSE;\n"
		"\t}\n"
		"\tsqlite3_busy_timeout(pDb, 3000);\n"
		"\tbOK = sqlite3_exec(pDb, CONTENT_PLUGIN_SCHEMA_SQL, NULL, NULL, &sError) == SQLITE_OK;\n"
		"\tif ( sError ) sqlite3_free(sError);\n"
		"\tsqlite3_close(pDb);\n"
		"\treturn bOK;\n"
		"}\n"
		"\n"
		"#endif\n",
		sTable ? (const char*)sTable : "content_record"
	);
	if ( sTable ) xrtFree(sTable);
	return sRet;
}

str Content_BuildGeneratedFieldRows(xvalue tblSpec)
{
	xvalue arrFields = tblSpec ? xvoTableGetValue(tblSpec, "fields", 6) : NULL;
	str sRows = xrtCopyStr("", 0);

	if ( arrFields && (xvoType(arrFields) == XVO_DT_ARRAY) ) {
		for ( uint32 i = 0; i < xvoArrayItemCount(arrFields); i++ ) {
			xvalue tblField = xvoArrayGetValue(arrFields, i);
			str sName = (tblField && (xvoType(tblField) == XVO_DT_TABLE)) ? xvoTableGetText(tblField, "name", 4) : (str)"";
			str sFieldTitle = (tblField && (xvoType(tblField) == XVO_DT_TABLE)) ? xvoTableGetText(tblField, "title", 5) : (str)"";
			str sType = (tblField && (xvoType(tblField) == XVO_DT_TABLE)) ? xvoTableGetText(tblField, "type", 4) : (str)"";
			str sSafeName = Content_EscapeHtml((const char*)sName);
			str sSafeTitle = Content_EscapeHtml((const char*)sFieldTitle);
			str sSafeType = Content_EscapeHtml((const char*)sType);
			str sNext = xrtFormat(
				"%s<tr><td>%s</td><td>%s</td><td>%s</td></tr>",
				Content_TextOr((const char*)sRows, ""),
				Content_TextOr((const char*)sSafeName, ""),
				Content_TextOr((const char*)sSafeTitle, ""),
				Content_TextOr((const char*)sSafeType, "")
			);
			if ( sSafeName ) xrtFree(sSafeName);
			if ( sSafeTitle ) xrtFree(sSafeTitle);
			if ( sSafeType ) xrtFree(sSafeType);
			if ( sRows ) xrtFree(sRows);
			sRows = sNext;
		}
	}
	return sRows;
}

str Content_BuildGeneratedContracts(const char* sModelXid, int iRevision, xvalue tblSpec)
{
	xvalue arrCapabilities = tblSpec ? xvoTableGetValue(tblSpec, "capabilities", 12) : NULL;
	str sCapabilities = arrCapabilities ? xrtStringifyJSON(arrCapabilities, FALSE, NULL) : xrtCopyStr("[]", 0);
	str sTemplate = Content_LoadGeneratorTemplate("plugin.contracts.json.tpl");
	char sRevision[32];

	snprintf(sRevision, sizeof(sRevision), "%d", iRevision);
	if ( sTemplate == NULL ) {
		sTemplate = xrtCopyStr("{\"model\":\"@@MODEL_XID@@\",\"revision\":@@REVISION@@,\"capabilities\":@@CAPABILITIES_JSON@@}\n", 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@MODEL_XID@@", sModelXid ? sModelXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "@@REVISION@@", sRevision);
	sTemplate = Content_TemplateSet(sTemplate, "@@CAPABILITIES_JSON@@", Content_TextOr((const char*)sCapabilities, "[]"));
	if ( sCapabilities ) xrtFree(sCapabilities);
	return sTemplate;
}

str Content_BuildGeneratedManaged(const char* sSpecJson)
{
	str sTemplate = Content_LoadGeneratorTemplate("plugin.managed.json.tpl");
	if ( sTemplate == NULL ) {
		return xrtCopyStr((str)(sSpecJson ? sSpecJson : "{}"), 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@MANAGED_JSON@@", sSpecJson ? sSpecJson : "{}");
	return sTemplate;
}

str Content_BuildGeneratedPublicHtml(const char* sTitle)
{
	str sTemplate = Content_LoadGeneratorTemplate("plugin.public.html.tpl");
	str sSafeTitle = Content_EscapeHtml(sTitle ? sTitle : "");
	if ( sTemplate == NULL ) {
		str sFallback = xrtFormat("<!doctype html><html><head><meta charset=\"utf-8\"><title>%s</title></head><body><h1>%s</h1></body></html>", Content_TextOr((const char*)sSafeTitle, ""), Content_TextOr((const char*)sSafeTitle, ""));
		if ( sSafeTitle ) xrtFree(sSafeTitle);
		return sFallback;
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@MODEL_TITLE@@", Content_TextOr((const char*)sSafeTitle, ""));
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	return sTemplate;
}

str Content_BuildGeneratedAdminHtml(const char* sPluginXid, const char* sModelXid, const char* sTitle, xvalue tblSpec)
{
	str sRows = Content_BuildGeneratedFieldRows(tblSpec);
	str sTemplate = Content_LoadGeneratorTemplate("plugin.admin.html.tpl");
	str sSafeTitle = Content_EscapeHtml(sTitle ? sTitle : "Generated Content Plugin");
	str sSafeModelXid = Content_EscapeHtml(sModelXid ? sModelXid : "");
	if ( sTemplate == NULL ) {
		str sFallback = xrtFormat(
			"<!doctype html><html><head><meta charset=\"utf-8\"><title>%s</title>"
			"<link rel=\"stylesheet\" href=\"/plugin-static/%s/css/admin.css\"></head>"
			"<body><div class=\"content-plugin\"><h1>%s</h1><p>Model: %s</p>"
			"<table><thead><tr><th>Name</th><th>Title</th><th>Type</th></tr></thead><tbody>%s</tbody></table>"
			"</div></body></html>",
			Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"),
			sPluginXid ? sPluginXid : "",
			Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"),
			Content_TextOr((const char*)sSafeModelXid, ""),
			Content_TextOr((const char*)sRows, "")
		);
		if ( sRows ) xrtFree(sRows);
		if ( sSafeTitle ) xrtFree(sSafeTitle);
		if ( sSafeModelXid ) xrtFree(sSafeModelXid);
		return sFallback;
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@PLUGIN_XID@@", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "@@MODEL_XID@@", Content_TextOr((const char*)sSafeModelXid, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@MODEL_TITLE@@", Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"));
	sTemplate = Content_TemplateSet(sTemplate, "@@FIELD_ROWS@@", Content_TextOr((const char*)sRows, ""));
	if ( sRows ) xrtFree(sRows);
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	if ( sSafeModelXid ) xrtFree(sSafeModelXid);
	return sTemplate;
}
