str Content_StripUtf8BomTake(str sText, uint32* pSize)
{
	size_t iLen;
	str sClean;

	if ( sText == NULL ) {
		return NULL;
	}
	iLen = pSize ? (size_t)(*pSize) : strlen(sText);
	if ( iLen < 3 ) {
		return sText;
	}
	if ( ((unsigned char)sText[0] != 0xEF) || ((unsigned char)sText[1] != 0xBB) || ((unsigned char)sText[2] != 0xBF) ) {
		return sText;
	}

	sClean = xrtCopyStr(sText + 3, iLen - 3);
	xrtFree(sText);
	if ( pSize ) {
		*pSize = sClean ? (uint32)(iLen - 3) : 0;
	}
	return sClean;
}

const char* Content_RawTextOr(const char* sText, const char* sFallback)
{
	if ( (sText != NULL) && (sText[0] != '\0') ) {
		return sText;
	}
	return sFallback ? sFallback : "";
}

str Content_EscapeJsonString(const char* sText)
{
	xbuffer_struct tBuf;
	char chZero = 0;

	if ( sText == NULL ) {
		return xrtCopyStr("", 0);
	}

	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + 16));
	for ( const char* p = sText; *p; p++ ) {
		char c = *p;
		if ( c == '\\' ) {
			xrtBufferAppend(&tBuf, "\\\\", 2, XBUF_BINARY);
		} else if ( c == '"' ) {
			xrtBufferAppend(&tBuf, "\\\"", 2, XBUF_BINARY);
		} else if ( c == '\n' ) {
			xrtBufferAppend(&tBuf, "\\n", 2, XBUF_BINARY);
		} else if ( c == '\r' ) {
			xrtBufferAppend(&tBuf, "\\r", 2, XBUF_BINARY);
		} else if ( c == '\t' ) {
			xrtBufferAppend(&tBuf, "\\t", 2, XBUF_BINARY);
		} else {
			xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
		}
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_BuildGeneratedPluginJson(const char* sPluginXid, const char* sPluginTitle, const char* sDescription)
{
	str sSafeTitle = Content_EscapeJsonString(Content_RawTextOr(sPluginTitle, "Generated Content Plugin"));
	str sSafeDescription = Content_EscapeJsonString(Content_RawTextOr(sDescription, "Generated by xAdmin built-in content system"));
	str sRet = xrtFormat(
		"{\n"
		"\t\"formatVersion\": 4,\n"
		"\t\"xid\": \"%s\",\n"
		"\t\"name\": \"%s\",\n"
		"\t\"title\": \"%s\",\n"
		"\t\"description\": \"%s\",\n"
		"\t\"version\": \"1.0.0\",\n"
		"\t\"author\": \"xAdmin\",\n"
		"\t\"kind\": \"singleton\",\n"
		"\t\"runtime\": {\"compiler\":\"tcc\",\"language\":\"c\"},\n"
		"\t\"resources\": {\"page\":\"page\",\"template\":\"template\",\"option\":\"option\",\"static\":\"static\"},\n"
		"\t\"build\": {\"entry\":\"generated/main.c\",\"sources\":[\"generated/main.c\"],\"defines\":[\"XADMIN_PLUGIN=1\"]},\n"
		"\t\"compat\": {\"minHostVersion\":\"4.0.0\",\"maxHostVersion\":\"5.0.0\",\"abiVersion\":4},\n"
		"\t\"capabilities\": [\"route.public\",\"route.admin\"],\n"
		"\t\"dependencies\": {\"plugins\":[],\"services\":[],\"features\":[]},\n"
		"\t\"contributes\": {\"menus\":[],\"routes\":[],\"hooks\":[],\"events\":[]},\n"
		"\t\"defaultConfig\": \"config.defaults.json\",\n"
		"\t\"configSchema\": \"config.schema.json\",\n"
		"\t\"xadminManaged\": {\"managed\":true,\"generator\":\"content\",\"managedBy\":\"content\",\"managedType\":\"generated-plugin\",\"generatedRoot\":\"generated\",\"runtimeRoot\":\"runtime\",\"customRoot\":\"custom\"}\n"
		"}\n",
		sPluginXid,
		sPluginXid,
		Content_RawTextOr((const char*)sSafeTitle, "Generated Content Plugin"),
		Content_RawTextOr((const char*)sSafeDescription, "Generated by xAdmin built-in content system")
	);
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	if ( sSafeDescription ) xrtFree(sSafeDescription);
	return sRet;
}

const char* Content_TextOr(const char* sText, const char* sFallback)
{
	if ( (sText != NULL) && (sText[0] != '\0') ) {
		return sText;
	}
	return sFallback ? sFallback : "";
}

str Content_SanitizeSqlIdent(const char* sText, const char* sFallback)
{
	xbuffer_struct tBuf;
	char chZero = 0;
	bool bHasChar = FALSE;

	xrtBufferInit(&tBuf, 64);
	if ( sText ) {
		for ( const char* p = sText; *p; p++ ) {
			char c = *p;
			if ( ((c >= 'a') && (c <= 'z')) || ((c >= 'A') && (c <= 'Z')) || ((c >= '0') && (c <= '9')) || (c == '_') ) {
				xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
				bHasChar = TRUE;
			} else if ( c == '.' || c == '-' ) {
				char chUnder = '_';
				xrtBufferAppend(&tBuf, &chUnder, 1, XBUF_BINARY);
				bHasChar = TRUE;
			}
		}
	}
	if ( !bHasChar ) {
		const char* sDefault = Content_TextOr(sFallback, "content_record");
		xrtBufferAppend(&tBuf, (ptr)sDefault, (uint32)strlen(sDefault), XBUF_BINARY);
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_TemplatePath(const char* sName)
{
	if ( (AppPath == NULL) || (sName == NULL) || (sName[0] == '\0') ) {
		return NULL;
	}
	if ( strncmp(sName, "managed_", 8) == 0 ) {
		return xrtPathJoin(5, AppPath, "data", "content", "templates", (str)sName);
	}
	return xrtPathJoin(5, AppPath, "data", "template", "content", (str)sName);
}

str Content_LoadGeneratorTemplate(const char* sName)
{
	str sPath;
	str sText = NULL;
	size_t iSize = 0;

	sPath = Content_TemplatePath(sName);
	if ( sPath && xrtFileExists(sPath) ) {
		sText = xrtFileGetAll(sPath, &iSize);
		sText = Content_StripUtf8BomTake(sText, &iSize);
	}
	if ( sPath ) {
		xrtFree(sPath);
	}
	return sText;
}

str Content_StringReplaceAll(const char* sText, const char* sNeedle, const char* sValue)
{
	xbuffer_struct tBuf;
	const char* p;
	const char* sCursor;
	size_t iNeedleLen;
	char chZero = 0;

	if ( sText == NULL ) {
		return NULL;
	}
	if ( (sNeedle == NULL) || (sNeedle[0] == '\0') ) {
		return xrtCopyStr((str)sText, 0);
	}
	if ( sValue == NULL ) {
		sValue = "";
	}

	iNeedleLen = strlen(sNeedle);
	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + strlen(sValue) + 32));
	sCursor = sText;
	while ( (p = strstr(sCursor, sNeedle)) != NULL ) {
		if ( p > sCursor ) {
			xrtBufferAppend(&tBuf, (ptr)sCursor, (uint32)(p - sCursor), XBUF_BINARY);
		}
		xrtBufferAppend(&tBuf, (ptr)sValue, (uint32)strlen(sValue), XBUF_BINARY);
		sCursor = p + iNeedleLen;
	}
	xrtBufferAppend(&tBuf, (ptr)sCursor, (uint32)strlen(sCursor), XBUF_BINARY);
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_TemplateSet(str sTemplate, const char* sNeedle, const char* sValue)
{
	str sNext = Content_StringReplaceAll(sTemplate, sNeedle, sValue);
	if ( sTemplate ) {
		xrtFree(sTemplate);
	}
	return sNext;
}

str Content_EscapeCString(const char* sText)
{
	xbuffer_struct tBuf;
	char chZero = 0;

	if ( sText == NULL ) {
		return xrtCopyStr("", 0);
	}

	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + 16));
	for ( const char* p = sText; *p; p++ ) {
		char c = *p;
		if ( c == '\\' ) {
			xrtBufferAppend(&tBuf, "\\\\", 2, XBUF_BINARY);
		} else if ( c == '"' ) {
			xrtBufferAppend(&tBuf, "\\\"", 2, XBUF_BINARY);
		} else if ( c == '\n' ) {
			xrtBufferAppend(&tBuf, "\\n", 2, XBUF_BINARY);
		} else if ( c == '\r' ) {
			xrtBufferAppend(&tBuf, "\\r", 2, XBUF_BINARY);
		} else {
			xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
		}
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_EscapeHtml(const char* sText)
{
	xbuffer_struct tBuf;
	char chZero = 0;

	if ( sText == NULL ) {
		return xrtCopyStr("", 0);
	}

	xrtBufferInit(&tBuf, (uint32)(strlen(sText) + 16));
	for ( const char* p = sText; *p; p++ ) {
		char c = *p;
		if ( c == '&' ) {
			xrtBufferAppend(&tBuf, "&amp;", 5, XBUF_BINARY);
		} else if ( c == '<' ) {
			xrtBufferAppend(&tBuf, "&lt;", 4, XBUF_BINARY);
		} else if ( c == '>' ) {
			xrtBufferAppend(&tBuf, "&gt;", 4, XBUF_BINARY);
		} else if ( c == '"' ) {
			xrtBufferAppend(&tBuf, "&quot;", 6, XBUF_BINARY);
		} else if ( c == '\'' ) {
			xrtBufferAppend(&tBuf, "&#39;", 5, XBUF_BINARY);
		} else {
			xrtBufferAppend(&tBuf, &c, 1, XBUF_BINARY);
		}
	}
	xrtBufferAppend(&tBuf, &chZero, 1, XBUF_BINARY);
	return (str)tBuf.Buffer;
}

str Content_BuildGeneratedMainC(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("plugin.main.c.tpl");
	str sRoute = xrtFormat("/admin/view/plugin/%s", sPluginXid ? sPluginXid : "");
	str sPublicRoute = xrtFormat("/content/%s", sPluginXid ? sPluginXid : "");
	str sOptionRoute = xrtFormat("/admin/view/form?source=plugin-option&plugin=%s&file=runtime.json", sPluginXid ? sPluginXid : "");
	if ( sTemplate == NULL ) {
		if ( sRoute ) xrtFree(sRoute);
		if ( sPublicRoute ) xrtFree(sPublicRoute);
		if ( sOptionRoute ) xrtFree(sOptionRoute);
		return xrtCopyStr("", 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@ADMIN_ROUTE@@", Content_TextOr((const char*)sRoute, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@PUBLIC_ROUTE@@", Content_TextOr((const char*)sPublicRoute, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@OPTION_ROUTE@@", Content_TextOr((const char*)sOptionRoute, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@PLUGIN_XID@@", sPluginXid ? sPluginXid : "");
	if ( sRoute ) xrtFree(sRoute);
	if ( sPublicRoute ) xrtFree(sPublicRoute);
	if ( sOptionRoute ) xrtFree(sOptionRoute);
	return sTemplate;
}

str Content_BuildPluginDomIdBase(const char* sPluginXid)
{
	const char* sBase = sPluginXid ? sPluginXid : "";
	const char* sPrefix = "Content_MakePlugin_";
	size_t iPrefixLen = strlen(sPrefix);
	size_t iBaseLen = strlen(sBase);
	char* sOut = (char*)xrtMalloc(iPrefixLen + iBaseLen + 1);
	size_t iPos = 0;

	if ( sOut == NULL ) {
		return NULL;
	}
	memcpy(sOut, sPrefix, iPrefixLen);
	iPos = iPrefixLen;
	for ( size_t i = 0; i < iBaseLen; i++ ) {
		char ch = sBase[i];
		if ( ((ch >= 'a') && (ch <= 'z')) || ((ch >= 'A') && (ch <= 'Z')) || ((ch >= '0') && (ch <= '9')) ) {
			sOut[iPos++] = ch;
		} else {
			sOut[iPos++] = '_';
		}
	}
	sOut[iPos] = '\0';
	return sOut;
}

str Content_BuildAbilityPackRouteCode(const char* sPluginXid, xvalue tblSpec)
{
	xvalue arrPacks = tblSpec ? xvoTableGetValue(tblSpec, "capabilities", 12) : NULL;
	str sCode = xrtCopyStr("", 0);

	if ( (arrPacks == NULL) || (xvoType(arrPacks) != XVO_DT_ARRAY) ) {
		return sCode;
	}
	for ( uint32 i = 0; i < xvoArrayItemCount(arrPacks); i++ ) {
		xvalue tblItem = xvoArrayGetValue(arrPacks, i);
		str sKey = (tblItem && (xvoType(tblItem) == XVO_DT_TABLE)) ? xvoTableGetText(tblItem, "key", 3) : NULL;
		str sSafeKey = NULL;
		str sNext = NULL;
		bool bEnabled = TRUE;

		if ( (sKey == NULL) || (sKey[0] == '\0') ) continue;
		if ( xvoTableExists(tblItem, "enabled", 7) ) bEnabled = xvoTableGetBool(tblItem, "enabled", 7);
		if ( !bEnabled ) continue;

		sSafeKey = Content_SanitizeSqlIdent((const char*)sKey, "pack");
		sNext = xrtFormat(
			"%s\t\tmemset(&route, 0, sizeof(route));\n"
			"\t\troute.path = \"/admin/view/plugin/%s/pack/%s\";\n"
			"\t\troute.proc = Managed_RequestAbilityPackView;\n"
			"\t\troute.need_auth = TRUE;\n"
			"\t\troute.admin_only = TRUE;\n"
			"\t\troute.auth_id = auth_%s;\n"
			"\t\tif ( XAdmin_RegisterRoute(handle, &route, NULL) != 0 ) {\n"
			"\t\t\tprintf(\"        [ManagedPlugin] ability route register failed: xid=%s path=%%s\\n\", route.path);\n"
			"\t\t\tgoto failed;\n"
			"\t\t}\n\n",
			Content_TextOr((const char*)sCode, ""),
			Content_TextOr(sPluginXid, ""),
			Content_TextOr((const char*)sSafeKey, "pack"),
			Content_TextOr((const char*)sSafeKey, "pack"),
			Content_TextOr(sPluginXid, "")
		);
		if ( sCode ) xrtFree(sCode);
		if ( sSafeKey ) xrtFree(sSafeKey);
		sCode = sNext;
	}
	return sCode;
}

const char* Content_DefaultAbilityPermission(const char* sPackId)
{
	if ( sPackId == NULL ) return "ability.manage";
	if ( strcmp(sPackId, "content.comment") == 0 ) return "comment.view";
	if ( strcmp(sPackId, "content.tag") == 0 ) return "tag.manage";
	if ( strcmp(sPackId, "content.topic") == 0 ) return "topic.manage";
	if ( strcmp(sPackId, "content.sensitive") == 0 ) return "sensitive.manage";
	if ( strcmp(sPackId, "content.static") == 0 ) return "static.manage";
	if ( strcmp(sPackId, "content.like") == 0 ) return "like.view";
	if ( strcmp(sPackId, "content.view-stat") == 0 ) return "view_stat.view";
	return "ability.manage";
}

bool Content_IsBuiltinAbilityPack(const char* sPackId)
{
	if ( sPackId == NULL ) return FALSE;
	if ( strcmp(sPackId, "content.comment") == 0 ) return TRUE;
	if ( strcmp(sPackId, "content.tag") == 0 ) return TRUE;
	if ( strcmp(sPackId, "content.topic") == 0 ) return TRUE;
	if ( strcmp(sPackId, "content.sensitive") == 0 ) return TRUE;
	if ( strcmp(sPackId, "content.static") == 0 ) return TRUE;
	if ( strcmp(sPackId, "content.like") == 0 ) return TRUE;
	if ( strcmp(sPackId, "content.view-stat") == 0 ) return TRUE;
	return FALSE;
}

str Content_BuildAbilityPackAuthCode(const char* sPluginXid, const char* sPluginTitle, xvalue tblSpec)
{
	xvalue arrPacks = tblSpec ? xvoTableGetValue(tblSpec, "capabilities", 12) : NULL;
	str sCode = xrtCopyStr("", 0);
	str sSafeGroupName = Content_EscapeCString(Content_TextOr(sPluginTitle, sPluginXid ? sPluginXid : "Generated Content Plugin"));
	bool bHasPack = FALSE;

	if ( (arrPacks == NULL) || (xvoType(arrPacks) != XVO_DT_ARRAY) ) {
		if ( sSafeGroupName ) xrtFree(sSafeGroupName);
		return sCode;
	}
	for ( uint32 i = 0; i < xvoArrayItemCount(arrPacks); i++ ) {
		xvalue tblItem = xvoArrayGetValue(arrPacks, i);
		str sKey = (tblItem && (xvoType(tblItem) == XVO_DT_TABLE)) ? xvoTableGetText(tblItem, "key", 3) : NULL;
		bool bEnabled = TRUE;
		if ( (sKey == NULL) || (sKey[0] == '\0') ) continue;
		if ( xvoTableExists(tblItem, "enabled", 7) ) bEnabled = xvoTableGetBool(tblItem, "enabled", 7);
		if ( !bEnabled ) continue;
		bHasPack = TRUE;
		break;
	}
	if ( !bHasPack ) {
		if ( sSafeGroupName ) xrtFree(sSafeGroupName);
		return sCode;
	}

	if ( sCode ) xrtFree(sCode);
	sCode = xrtFormat(
		"\tmemset(&authGroup, 0, sizeof(authGroup));\n"
		"\tauthGroup.scope = XADMIN_AUTH_SCOPE_ADMIN;\n"
		"\tauthGroup.name = \"%s Ability Packs\";\n"
		"\tauthGroup.description = \"Generated content ability pack permissions\";\n"
		"\tauthGroup.sort = 700000;\n"
		"\tif ( XAdmin_RegisterAuthGroup(handle, &authGroup, &iAbilityAuthGroupId, NULL) != 0 ) goto failed;\n\n",
		Content_TextOr((const char*)sSafeGroupName, "")
	);

	for ( uint32 i = 0; i < xvoArrayItemCount(arrPacks); i++ ) {
		xvalue tblItem = xvoArrayGetValue(arrPacks, i);
		str sKey = (tblItem && (xvoType(tblItem) == XVO_DT_TABLE)) ? xvoTableGetText(tblItem, "key", 3) : NULL;
		str sSafeKey = NULL;
		xvalue tblPack = NULL;
		xvalue tblContracts = NULL;
		xvalue arrPermissions = NULL;
		str sContractsJson = NULL;
		bool bEnabled = TRUE;
		bool bDeclaredFirst = FALSE;
		bool bBuiltinPack = FALSE;
		const char* sFallbackPerm;

		if ( (sKey == NULL) || (sKey[0] == '\0') ) continue;
		if ( xvoTableExists(tblItem, "enabled", 7) ) bEnabled = xvoTableGetBool(tblItem, "enabled", 7);
		if ( !bEnabled ) continue;

		sSafeKey = Content_SanitizeSqlIdent((const char*)sKey, "pack");
		bBuiltinPack = Content_IsBuiltinAbilityPack((const char*)sKey);
		sFallbackPerm = Content_DefaultAbilityPermission((const char*)sKey);
		tblPack = ContentPack_GetDetail((const char*)sKey);
		sContractsJson = tblPack ? xvoTableGetText(tblPack, "contractsJson", 13) : NULL;
		if ( sContractsJson && sContractsJson[0] ) {
			tblContracts = xrtParseJSON(sContractsJson, strlen(sContractsJson));
			arrPermissions = tblContracts ? xvoTableGetValue(tblContracts, "permissions", 11) : NULL;
		}
		if ( (arrPermissions == NULL) || (xvoType(arrPermissions) != XVO_DT_ARRAY) || (xvoArrayItemCount(arrPermissions) == 0) ) {
			arrPermissions = NULL;
		}
		{
			uint32 iPermCount = arrPermissions ? xvoArrayItemCount(arrPermissions) : 1;
			for ( uint32 j = 0; j < iPermCount; j++ ) {
				xvalue objPerm = arrPermissions ? xvoArrayGetValue(arrPermissions, j) : NULL;
				const char* sPerm = arrPermissions ? xvoGetText(objPerm) : sFallbackPerm;
				str sAuthName = NULL;
				str sAuthDesc = NULL;
				str sNext = NULL;
				if ( (sPerm == NULL) || (sPerm[0] == '\0') ) continue;
				sAuthName = xrtFormat("%s.%s", Content_TextOr(sPluginXid, ""), sPerm);
				sAuthDesc = xrtFormat("Ability pack permission: %s", sPerm);
				sNext = xrtFormat(
					"%s\tint auth_%s_%u = 0;\n"
					"\tmemset(&auth, 0, sizeof(auth));\n"
					"\tauth.scope = XADMIN_AUTH_SCOPE_ADMIN;\n"
					"\tauth.group_id = iAbilityAuthGroupId;\n"
					"\tauth.name = \"%s\";\n"
					"\tauth.description = \"%s\";\n"
					"\tauth.sort = %d;\n"
					"\tif ( XAdmin_RegisterAuth(handle, &auth, &auth_%s_%u, NULL) != 0 ) goto failed;\n",
					Content_TextOr((const char*)sCode, ""),
					Content_TextOr((const char*)sSafeKey, "pack"), j,
					Content_TextOr((const char*)sAuthName, ""),
					Content_TextOr((const char*)sAuthDesc, ""),
					700100 + ((int)i * 100) + (int)j,
					Content_TextOr((const char*)sSafeKey, "pack"), j
				);
				if ( sCode ) xrtFree(sCode);
				sCode = sNext;
				if ( !bDeclaredFirst ) {
					sNext = xrtFormat(
						bBuiltinPack ? "%s\tauth_%s = auth_%s_%u;\n" : "%s\tint auth_%s = auth_%s_%u;\n",
						Content_TextOr((const char*)sCode, ""),
						Content_TextOr((const char*)sSafeKey, "pack"),
						Content_TextOr((const char*)sSafeKey, "pack"),
						j
					);
					if ( sCode ) xrtFree(sCode);
					sCode = sNext;
					bDeclaredFirst = TRUE;
				}
				if ( sAuthName ) xrtFree(sAuthName);
				if ( sAuthDesc ) xrtFree(sAuthDesc);
			}
		}
		if ( !bDeclaredFirst ) {
			str sNext = xrtFormat(
				bBuiltinPack ? "%s\tauth_%s = 0;\n" : "%s\tint auth_%s = 0;\n",
				Content_TextOr((const char*)sCode, ""),
				Content_TextOr((const char*)sSafeKey, "pack")
			);
			if ( sCode ) xrtFree(sCode);
			sCode = sNext;
		}
		{
			str sNext = xrtFormat("%s\n", Content_TextOr((const char*)sCode, ""));
			if ( sCode ) xrtFree(sCode);
			sCode = sNext;
		}
		if ( tblContracts ) xvoUnref(tblContracts);
		if ( tblPack ) xvoUnref(tblPack);
		if ( sSafeKey ) xrtFree(sSafeKey);
	}
	if ( sSafeGroupName ) xrtFree(sSafeGroupName);
	return sCode;
}

str Content_BuildAbilityPackSchemaSql(xvalue tblSpec)
{
	xvalue arrPacks = tblSpec ? xvoTableGetValue(tblSpec, "capabilities", 12) : NULL;
	str sCode = xrtCopyStr("", 0);

	if ( (arrPacks == NULL) || (xvoType(arrPacks) != XVO_DT_ARRAY) ) {
		return sCode;
	}
	for ( uint32 i = 0; i < xvoArrayItemCount(arrPacks); i++ ) {
		xvalue tblItem = xvoArrayGetValue(arrPacks, i);
		str sKey = (tblItem && (xvoType(tblItem) == XVO_DT_TABLE)) ? xvoTableGetText(tblItem, "key", 3) : NULL;
		xvalue tblPack = NULL;
		str sDir = NULL;
		str sPath = NULL;
		str sSql = NULL;
		str sEscaped = NULL;
		str sNext = NULL;
		size_t iSize = 0;
		bool bEnabled = TRUE;

		if ( (sKey == NULL) || (sKey[0] == '\0') ) continue;
		if ( xvoTableExists(tblItem, "enabled", 7) ) bEnabled = xvoTableGetBool(tblItem, "enabled", 7);
		if ( !bEnabled ) continue;

		tblPack = ContentPack_GetDetail((const char*)sKey);
		sDir = tblPack ? xvoTableGetText(tblPack, "path", 4) : NULL;
		if ( (sDir == NULL) || (sDir[0] == '\0') ) {
			if ( tblPack ) xvoUnref(tblPack);
			continue;
		}
		sPath = xrtPathJoin(2, sDir, "schema.sql");
		if ( sPath && xrtFileExists(sPath) ) {
			sSql = xrtFileGetAll(sPath, &iSize);
		}
		if ( sSql && sSql[0] ) {
			sEscaped = Content_EscapeCString((const char*)sSql);
			sNext = xrtFormat("%s\n\t\"%s\"", Content_TextOr((const char*)sCode, ""), Content_TextOr((const char*)sEscaped, ""));
			if ( sCode ) xrtFree(sCode);
			sCode = sNext;
		}
		if ( sPath ) xrtFree(sPath);
		if ( sSql ) xrtFree(sSql);
		if ( sEscaped ) xrtFree(sEscaped);
		if ( tblPack ) xvoUnref(tblPack);
	}
	return sCode;
}

str Content_BuildAbilityPackMenuCode(const char* sPluginXid, xvalue tblSpec)
{
	xvalue arrPacks = tblSpec ? xvoTableGetValue(tblSpec, "capabilities", 12) : NULL;
	str sCode = xrtCopyStr("", 0);

	if ( (arrPacks == NULL) || (xvoType(arrPacks) != XVO_DT_ARRAY) ) {
		return sCode;
	}
	for ( uint32 i = 0; i < xvoArrayItemCount(arrPacks); i++ ) {
		xvalue tblItem = xvoArrayGetValue(arrPacks, i);
		str sKey = (tblItem && (xvoType(tblItem) == XVO_DT_TABLE)) ? xvoTableGetText(tblItem, "key", 3) : NULL;
		str sSafeKey = NULL;
		str sSafeTitle = NULL;
		str sNext = NULL;
		xvalue tblPack = NULL;
		str sTitle = NULL;
		bool bEnabled = TRUE;

		if ( (sKey == NULL) || (sKey[0] == '\0') ) continue;
		if ( xvoTableExists(tblItem, "enabled", 7) ) bEnabled = xvoTableGetBool(tblItem, "enabled", 7);
		if ( !bEnabled ) continue;

		tblPack = ContentPack_GetDetail((const char*)sKey);
		sTitle = tblPack ? xvoTableGetText(tblPack, "title", 5) : sKey;
		sSafeKey = Content_SanitizeSqlIdent((const char*)sKey, "pack");
		sSafeTitle = Content_EscapeCString(Content_TextOr((const char*)sTitle, (const char*)sKey));
		sNext = xrtFormat(
			"%s\t\tmemset(&menu, 0, sizeof(menu));\n"
			"\t\tmenu.key = \"%s.pack.%s\";\n"
			"\t\tmenu.parent_id = iRootMenuId;\n"
			"\t\tmenu.title = \"%s\";\n"
			"\t\tmenu.icon = \"layui-icon layui-icon-component\";\n"
			"\t\tmenu.type = 1;\n"
			"\t\tmenu.open_type = \"_component\";\n"
			"\t\tmenu.href = \"/admin/view/plugin/%s/pack/%s\";\n"
			"\t\tmenu.sort = %d;\n"
			"\t\tmenu.visible = TRUE;\n"
			"\t\tmenu.remark = \"Generated ability pack admin page\";\n"
			"\t\tif ( XAdmin_RegisterMenu(handle, &menu, NULL, NULL) != 0 ) {\n"
			"\t\t\tprintf(\"        [ManagedPlugin] ability menu register failed: xid=%s href=%%s\\n\", menu.href);\n"
			"\t\t\tgoto failed;\n"
			"\t\t}\n\n",
			Content_TextOr((const char*)sCode, ""),
			Content_TextOr(sPluginXid, ""),
			Content_TextOr((const char*)sSafeKey, "pack"),
			Content_TextOr((const char*)sSafeTitle, ""),
			Content_TextOr(sPluginXid, ""),
			Content_TextOr((const char*)sSafeKey, "pack"),
			100 + ((int)i * 10),
			Content_TextOr(sPluginXid, "")
		);
		if ( sCode ) xrtFree(sCode);
		if ( sSafeKey ) xrtFree(sSafeKey);
		if ( sSafeTitle ) xrtFree(sSafeTitle);
		if ( tblPack ) xvoUnref(tblPack);
		sCode = sNext;
	}
	return sCode;
}

str Content_BuildManagedMainC(const char* sPluginXid, const char* sPluginTitle, const char* sMenuTitle, xvalue tblSpec)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_main.c.tpl");
	str sSafePluginTitle = Content_EscapeCString(Content_TextOr(sPluginTitle, sPluginXid ? sPluginXid : "Generated Content Plugin"));
	str sSafeMenuTitle = Content_EscapeCString(Content_TextOr(sMenuTitle, sPluginTitle ? sPluginTitle : (sPluginXid ? sPluginXid : "Generated Content Plugin")));
	str sPackRoutes = NULL;
	str sPackMenus = NULL;
	str sPackSchemaSql = NULL;
	str sPackAuth = NULL;
	if ( sTemplate == NULL ) {
		if ( sSafePluginTitle ) xrtFree(sSafePluginTitle);
		if ( sSafeMenuTitle ) xrtFree(sSafeMenuTitle);
		return xrtCopyStr("", 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_TITLE_C}}", Content_TextOr((const char*)sSafePluginTitle, ""));
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_VERSION}}", "1.0.0");
	sPackRoutes = Content_BuildAbilityPackRouteCode(sPluginXid, tblSpec);
	sPackMenus = Content_BuildAbilityPackMenuCode(sPluginXid, tblSpec);
	sPackSchemaSql = Content_BuildAbilityPackSchemaSql(tblSpec);
	sPackAuth = Content_BuildAbilityPackAuthCode(sPluginXid, sPluginTitle, tblSpec);
	sTemplate = Content_TemplateSet(sTemplate, "{{ABILITY_PACK_ROUTE_REGISTRATIONS}}", Content_TextOr((const char*)sPackRoutes, ""));
	sTemplate = Content_TemplateSet(sTemplate, "{{ABILITY_PACK_MENU_REGISTRATIONS}}", Content_TextOr((const char*)sPackMenus, ""));
	sTemplate = Content_TemplateSet(sTemplate, "{{ABILITY_PACK_SCHEMA_SQL}}", Content_TextOr((const char*)sPackSchemaSql, ""));
	sTemplate = Content_TemplateSet(sTemplate, "{{ABILITY_PACK_AUTH_REGISTRATIONS}}", Content_TextOr((const char*)sPackAuth, ""));
	if ( sSafeMenuTitle && sPluginTitle && sMenuTitle && strcmp((const char*)sPluginTitle, (const char*)sMenuTitle) != 0 ) {
		str sNeedle = xrtFormat("menu.title = \"%s\";", Content_TextOr((const char*)sSafePluginTitle, ""));
		str sValue = xrtFormat("menu.title = \"%s\";", Content_TextOr((const char*)sSafeMenuTitle, ""));
		if ( sNeedle && sValue ) {
			sTemplate = Content_TemplateSet(sTemplate, sNeedle, sValue);
		}
		if ( sNeedle ) xrtFree(sNeedle);
		if ( sValue ) xrtFree(sValue);
	}
	if ( sSafePluginTitle ) xrtFree(sSafePluginTitle);
	if ( sSafeMenuTitle ) xrtFree(sSafeMenuTitle);
	if ( sPackRoutes ) xrtFree(sPackRoutes);
	if ( sPackMenus ) xrtFree(sPackMenus);
	if ( sPackSchemaSql ) xrtFree(sPackSchemaSql);
	if ( sPackAuth ) xrtFree(sPackAuth);
	return sTemplate;
}

str Content_BuildManagedAdminPageHtml(const char* sPluginXid, const char* sPageKind)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_admin.html.tpl");
	str sDomIdBase = Content_BuildPluginDomIdBase(sPluginXid);
	str sPageDomIdBase = NULL;
	if ( sTemplate == NULL ) {
		if ( sDomIdBase ) xrtFree(sDomIdBase);
		return NULL;
	}
	sPageDomIdBase = xrtFormat("%s_%s", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin", (sPageKind && strcmp(sPageKind, "drafts") == 0) ? "Drafts" : "Articles");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_DOM_ID_BASE}}", sPageDomIdBase ? (const char*)sPageDomIdBase : (sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin"));
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_PAGE_KIND}}", sPageKind ? sPageKind : "articles");
	if ( sPageDomIdBase ) xrtFree(sPageDomIdBase);
	if ( sDomIdBase ) xrtFree(sDomIdBase);
	return sTemplate;
}

str Content_BuildManagedEditorHtml(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_editor.html.tpl");
	str sDomIdBase = Content_BuildPluginDomIdBase(sPluginXid);
	str sPageDomIdBase = NULL;
	if ( sTemplate == NULL ) {
		if ( sDomIdBase ) xrtFree(sDomIdBase);
		return NULL;
	}
	sPageDomIdBase = xrtFormat("%s_Editor", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_DOM_ID_BASE}}", sPageDomIdBase ? (const char*)sPageDomIdBase : (sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin_Editor"));
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_LIST_DOM_ID_BASE}}", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin");
	if ( sPageDomIdBase ) xrtFree(sPageDomIdBase);
	if ( sDomIdBase ) xrtFree(sDomIdBase);
	return sTemplate;
}

str Content_BuildManagedCategoryHtml(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_category.html.tpl");
	str sDomIdBase = Content_BuildPluginDomIdBase(sPluginXid);
	str sPageDomIdBase = NULL;
	if ( sTemplate == NULL ) {
		if ( sDomIdBase ) xrtFree(sDomIdBase);
		return NULL;
	}
	sPageDomIdBase = xrtFormat("%s_Categories", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_DOM_ID_BASE}}", sPageDomIdBase ? (const char*)sPageDomIdBase : (sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin_Category"));
	if ( sPageDomIdBase ) xrtFree(sPageDomIdBase);
	if ( sDomIdBase ) xrtFree(sDomIdBase);
	return sTemplate;
}

str Content_BuildManagedPublicHtml(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_public.html.tpl");
	str sDomIdBase = Content_BuildPluginDomIdBase(sPluginXid);
	if ( sTemplate == NULL ) {
		if ( sDomIdBase ) xrtFree(sDomIdBase);
		return NULL;
	}
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_XID}}", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_DOM_ID_BASE}}", sDomIdBase ? (const char*)sDomIdBase : "Content_MakePlugin");
	sTemplate = Content_TemplateSet(sTemplate, "{{PLUGIN_PAGE_KIND}}", "public");
	if ( sDomIdBase ) xrtFree(sDomIdBase);
	return sTemplate;
}

str Content_BuildManagedAbilityHtml(const char* sPluginXid)
{
	str sTemplate = Content_LoadGeneratorTemplate("managed_ability.html.tpl");
	if ( sTemplate == NULL ) {
		return xrtCopyStr("<div style=\"padding:16px;\">Ability pack page missing.</div>", 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@PLUGIN_XID@@", sPluginXid ? sPluginXid : "");
	return sTemplate;
}

str Content_BuildGeneratedModelH(const char* sModelXid, const char* sTitle, const char* sPluginTitle, const char* sMenuTitle)
{
	str sSafeXid = Content_EscapeCString(sModelXid);
	str sSafeTitle = Content_EscapeCString(sTitle ? sTitle : "Generated Content Plugin");
	str sSafePluginTitle = Content_EscapeCString(Content_TextOr(sPluginTitle, sTitle ? sTitle : "Generated Content Plugin"));
	str sSafeMenuTitle = Content_EscapeCString(Content_TextOr(sMenuTitle, sTitle ? sTitle : "Generated Content Plugin"));
	str sRet;

	sRet = xrtFormat(
		"#ifndef CONTENT_PLUGIN_MODEL_H\n"
		"#define CONTENT_PLUGIN_MODEL_H\n"
		"\n"
		"#define CONTENT_MODEL_XID \"%s\"\n"
		"#define CONTENT_MODEL_TITLE \"%s\"\n"
		"#define CONTENT_PLUGIN_TITLE \"%s\"\n"
		"#define CONTENT_MENU_TITLE \"%s\"\n"
		"\n"
		"#endif\n",
		Content_TextOr((const char*)sSafeXid, ""),
		Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"),
		Content_TextOr((const char*)sSafePluginTitle, "Generated Content Plugin"),
		Content_TextOr((const char*)sSafeMenuTitle, "Generated Content Plugin")
	);
	if ( sSafeXid ) xrtFree(sSafeXid);
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	if ( sSafePluginTitle ) xrtFree(sSafePluginTitle);
	if ( sSafeMenuTitle ) xrtFree(sSafeMenuTitle);
	return sRet;
}

str Content_BuildGeneratedDbH(const char* sTableName)
{
	str sTable = Content_SanitizeSqlIdent(sTableName, "content_record");
	str sRet = xrtFormat(
		"#ifndef CONTENT_PLUGIN_DB_H\n"
		"#define CONTENT_PLUGIN_DB_H\n"
		"\n"
		"static const char* CONTENT_PLUGIN_SCHEMA_SQL =\n"
		"\t\"CREATE TABLE IF NOT EXISTS %s (\"\n"
		"\t\"id INTEGER PRIMARY KEY AUTOINCREMENT,\"\n"
		"\t\"status INTEGER NOT NULL DEFAULT 0,\"\n"
		"\t\"payload_json TEXT NOT NULL DEFAULT '{}',\"\n"
		"\t\"create_time INTEGER NOT NULL,\"\n"
		"\t\"update_time INTEGER NOT NULL DEFAULT 0,\"\n"
		"\t\"delete_time INTEGER NOT NULL DEFAULT 0\"\n"
		"\t\");\";\n"
		"\n"
		"static bool ContentPlugin_EnsureSchema(const char* sPrivateDbPath)\n"
		"{\n"
		"\tsqlite3* pDb = NULL;\n"
		"\tchar* sError = NULL;\n"
		"\tbool bOK = FALSE;\n"
		"\tif ( (sPrivateDbPath == NULL) || (sPrivateDbPath[0] == '\\0') ) return FALSE;\n"
		"\tif ( sqlite3_open_v2(sPrivateDbPath, &pDb, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_FULLMUTEX, NULL) != SQLITE_OK ) {\n"
		"\t\tif ( pDb ) sqlite3_close(pDb);\n"
		"\t\treturn FALSE;\n"
		"\t}\n"
		"\tsqlite3_busy_timeout(pDb, 3000);\n"
		"\tbOK = sqlite3_exec(pDb, CONTENT_PLUGIN_SCHEMA_SQL, NULL, NULL, &sError) == SQLITE_OK;\n"
		"\tif ( sError ) sqlite3_free(sError);\n"
		"\tsqlite3_close(pDb);\n"
		"\treturn bOK;\n"
		"}\n"
		"\n"
		"#endif\n",
		sTable ? (const char*)sTable : "content_record"
	);
	if ( sTable ) xrtFree(sTable);
	return sRet;
}

str Content_BuildGeneratedFieldRows(xvalue tblSpec)
{
	xvalue arrFields = tblSpec ? xvoTableGetValue(tblSpec, "fields", 6) : NULL;
	str sRows = xrtCopyStr("", 0);

	if ( arrFields && (xvoType(arrFields) == XVO_DT_ARRAY) ) {
		for ( uint32 i = 0; i < xvoArrayItemCount(arrFields); i++ ) {
			xvalue tblField = xvoArrayGetValue(arrFields, i);
			str sName = (tblField && (xvoType(tblField) == XVO_DT_TABLE)) ? xvoTableGetText(tblField, "name", 4) : (str)"";
			str sFieldTitle = (tblField && (xvoType(tblField) == XVO_DT_TABLE)) ? xvoTableGetText(tblField, "title", 5) : (str)"";
			str sType = (tblField && (xvoType(tblField) == XVO_DT_TABLE)) ? xvoTableGetText(tblField, "type", 4) : (str)"";
			str sSafeName = Content_EscapeHtml((const char*)sName);
			str sSafeTitle = Content_EscapeHtml((const char*)sFieldTitle);
			str sSafeType = Content_EscapeHtml((const char*)sType);
			str sNext = xrtFormat(
				"%s<tr><td>%s</td><td>%s</td><td>%s</td></tr>",
				Content_TextOr((const char*)sRows, ""),
				Content_TextOr((const char*)sSafeName, ""),
				Content_TextOr((const char*)sSafeTitle, ""),
				Content_TextOr((const char*)sSafeType, "")
			);
			if ( sSafeName ) xrtFree(sSafeName);
			if ( sSafeTitle ) xrtFree(sSafeTitle);
			if ( sSafeType ) xrtFree(sSafeType);
			if ( sRows ) xrtFree(sRows);
			sRows = sNext;
		}
	}
	return sRows;
}

str Content_BuildGeneratedContracts(const char* sModelXid, int iRevision, xvalue tblSpec)
{
	xvalue arrCapabilities = tblSpec ? xvoTableGetValue(tblSpec, "capabilities", 12) : NULL;
	xvalue tblRoot = xvoCreateTable();
	xvalue arrPacks = xvoCreateArray();
	str sJson;

	xvoTableSetText(tblRoot, "model", 5, (str)Content_TextOr(sModelXid, ""), 0, FALSE);
	xvoTableSetInt(tblRoot, "revision", 8, iRevision);
	xvoTableSetText(tblRoot, "permissionBinding", 17, "ability-admin-page-bound", 0, FALSE);
	xvoTableSetText(tblRoot, "permissionBindingNote", 21, "Ability permissions are registered and each mounted ability admin page route is bound to the first permission declared by that ability pack.", 0, FALSE);
	if ( arrCapabilities && xvoType(arrCapabilities) == XVO_DT_ARRAY ) {
		xvoTableSetValue(tblRoot, "capabilities", 12, xvoCopy(arrCapabilities), TRUE);
		for ( uint32 i = 0; i < xvoArrayItemCount(arrCapabilities); i++ ) {
			xvalue tblItem = xvoArrayGetValue(arrCapabilities, i);
			str sKey = (tblItem && xvoType(tblItem) == XVO_DT_TABLE) ? xvoTableGetText(tblItem, "key", 3) : NULL;
			xvalue tblPack = NULL;
			xvalue tblOut = NULL;
			xvalue objJson = NULL;
			str sJsonText = NULL;
			bool bEnabled = TRUE;

			if ( (sKey == NULL) || (sKey[0] == '\0') ) {
				continue;
			}
			if ( xvoTableExists(tblItem, "enabled", 7) ) {
				bEnabled = xvoTableGetBool(tblItem, "enabled", 7);
			}
			if ( !bEnabled ) {
				continue;
			}
			tblPack = ContentPack_GetDetail((const char*)sKey);
			tblOut = xvoCreateTable();
			xvoTableSetText(tblOut, "packId", 6, sKey, 0, FALSE);
			xvoTableSetText(tblOut, "permissionBinding", 17, "ability-admin-page-bound", 0, FALSE);
			if ( tblPack && (xvoType(tblPack) == XVO_DT_TABLE) ) {
				xvoTableSetText(tblOut, "title", 5, xvoTableGetText(tblPack, "title", 5), 0, FALSE);
				xvoTableSetText(tblOut, "version", 7, xvoTableGetText(tblPack, "version", 7), 0, FALSE);
				xvoTableSetText(tblOut, "description", 11, xvoTableGetText(tblPack, "description", 11), 0, FALSE);
				sJsonText = xvoTableGetText(tblPack, "effectsJson", 11);
				objJson = sJsonText ? xrtParseJSON(sJsonText, strlen(sJsonText)) : NULL;
				if ( objJson ) xvoTableSetValue(tblOut, "effects", 7, objJson, TRUE);
				sJsonText = xvoTableGetText(tblPack, "contractsJson", 13);
				objJson = sJsonText ? xrtParseJSON(sJsonText, strlen(sJsonText)) : NULL;
				if ( objJson ) xvoTableSetValue(tblOut, "contracts", 9, objJson, TRUE);
				sJsonText = xvoTableGetText(tblPack, "hooksJson", 9);
				objJson = sJsonText ? xrtParseJSON(sJsonText, strlen(sJsonText)) : NULL;
				if ( objJson ) xvoTableSetValue(tblOut, "hooks", 5, objJson, TRUE);
			}
			if ( tblItem && (xvoType(tblItem) == XVO_DT_TABLE) ) {
				xvalue tblConfig = xvoTableGetValue(tblItem, "config", 6);
				xvalue tblMount = xvoTableGetValue(tblItem, "mount", 5);
				if ( tblConfig ) xvoTableSetValue(tblOut, "instanceConfig", 14, xvoCopy(tblConfig), TRUE);
				if ( tblMount ) xvoTableSetValue(tblOut, "mount", 5, xvoCopy(tblMount), TRUE);
			}
			xvoArrayAppendValue(arrPacks, tblOut, TRUE);
			if ( tblPack ) xvoUnref(tblPack);
		}
	} else {
		xvoTableSetValue(tblRoot, "capabilities", 12, xvoCreateArray(), TRUE);
	}
	xvoTableSetValue(tblRoot, "abilityPacks", 12, arrPacks, TRUE);
	sJson = xrtStringifyJSON(tblRoot, TRUE, NULL);
	xvoUnref(tblRoot);
	return sJson ? sJson : xrtCopyStr("{\"capabilities\":[],\"abilityPacks\":[]}\n", 0);
}

str Content_BuildGeneratedManaged(const char* sSpecJson)
{
	str sTemplate = Content_LoadGeneratorTemplate("plugin.managed.json.tpl");
	if ( sTemplate == NULL ) {
		return xrtCopyStr((str)(sSpecJson ? sSpecJson : "{}"), 0);
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@MANAGED_JSON@@", sSpecJson ? sSpecJson : "{}");
	return sTemplate;
}

str Content_BuildGeneratedPublicHtml(const char* sTitle)
{
	str sTemplate = Content_LoadGeneratorTemplate("plugin.public.html.tpl");
	str sSafeTitle = Content_EscapeHtml(sTitle ? sTitle : "");
	if ( sTemplate == NULL ) {
		str sFallback = xrtFormat("<!doctype html><html><head><meta charset=\"utf-8\"><title>%s</title></head><body><h1>%s</h1></body></html>", Content_TextOr((const char*)sSafeTitle, ""), Content_TextOr((const char*)sSafeTitle, ""));
		if ( sSafeTitle ) xrtFree(sSafeTitle);
		return sFallback;
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@MODEL_TITLE@@", Content_TextOr((const char*)sSafeTitle, ""));
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	return sTemplate;
}

str Content_BuildGeneratedAdminHtml(const char* sPluginXid, const char* sModelXid, const char* sTitle, xvalue tblSpec)
{
	str sRows = Content_BuildGeneratedFieldRows(tblSpec);
	str sTemplate = Content_LoadGeneratorTemplate("plugin.admin.html.tpl");
	str sSafeTitle = Content_EscapeHtml(sTitle ? sTitle : "Generated Content Plugin");
	str sSafeModelXid = Content_EscapeHtml(sModelXid ? sModelXid : "");
	if ( sTemplate == NULL ) {
		str sFallback = xrtFormat(
			"<!doctype html><html><head><meta charset=\"utf-8\"><title>%s</title>"
			"<link rel=\"stylesheet\" href=\"/plugin-static/%s/css/admin.css\"></head>"
			"<body><div class=\"content-plugin\"><h1>%s</h1><p>Model: %s</p>"
			"<table><thead><tr><th>Name</th><th>Title</th><th>Type</th></tr></thead><tbody>%s</tbody></table>"
			"</div></body></html>",
			Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"),
			sPluginXid ? sPluginXid : "",
			Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"),
			Content_TextOr((const char*)sSafeModelXid, ""),
			Content_TextOr((const char*)sRows, "")
		);
		if ( sRows ) xrtFree(sRows);
		if ( sSafeTitle ) xrtFree(sSafeTitle);
		if ( sSafeModelXid ) xrtFree(sSafeModelXid);
		return sFallback;
	}
	sTemplate = Content_TemplateSet(sTemplate, "@@PLUGIN_XID@@", sPluginXid ? sPluginXid : "");
	sTemplate = Content_TemplateSet(sTemplate, "@@MODEL_XID@@", Content_TextOr((const char*)sSafeModelXid, ""));
	sTemplate = Content_TemplateSet(sTemplate, "@@MODEL_TITLE@@", Content_TextOr((const char*)sSafeTitle, "Generated Content Plugin"));
	sTemplate = Content_TemplateSet(sTemplate, "@@FIELD_ROWS@@", Content_TextOr((const char*)sRows, ""));
	if ( sRows ) xrtFree(sRows);
	if ( sSafeTitle ) xrtFree(sSafeTitle);
	if ( sSafeModelXid ) xrtFree(sSafeModelXid);
	return sTemplate;
}
