CREATE TABLE IF NOT EXISTS tag (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL DEFAULT '',
slug TEXT NOT NULL DEFAULT '',
description TEXT NOT NULL DEFAULT '',
sort INTEGER NOT NULL DEFAULT 0,
status INTEGER NOT NULL DEFAULT 1,
content_count INTEGER NOT NULL DEFAULT 0,
create_time INTEGER NOT NULL DEFAULT 0,
update_time INTEGER NOT NULL DEFAULT 0,
delete_time INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS content_tag (
id INTEGER PRIMARY KEY AUTOINCREMENT,
content_id INTEGER NOT NULL DEFAULT 0,
tag_id INTEGER NOT NULL DEFAULT 0,
sort INTEGER NOT NULL DEFAULT 0,
create_time INTEGER NOT NULL DEFAULT 0,
UNIQUE(content_id, tag_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tag_slug ON tag(slug) WHERE delete_time = 0;
CREATE INDEX IF NOT EXISTS idx_tag_status_sort ON tag(status, sort, id);
CREATE INDEX IF NOT EXISTS idx_content_tag_tag ON content_tag(tag_id, sort, content_id);
